name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: task1-1
      id: task1-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task1-1
        setup-command: ''
        command: python3 Task1.py
        input: ''
        expected-output: Hello, world
        comparison-method: contains
        timeout: 10
    - name: task1-2
      id: task1-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task1-2
        setup-command: ''
        command: python3 Task1.py --name John
        input: ''
        expected-output: Hello, John
        comparison-method: contains
        timeout: 1
    - name: task1-3
      id: task1-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task1-3
        setup-command: ''
        command: python3 Task1.py John --name
        input: ''
        expected-output: Hello, world
        comparison-method: contains
        timeout: 1
    - name: task1-4
      id: task1-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task1-4
        setup-command: ''
        command: python3 Task1.py somearg --name Jane
        input: ''
        expected-output: Hello, Jane
        comparison-method: contains
        timeout: 1
    - name: task2-1
      id: task2-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task2-1
        setup-command: ''
        command: python3 Task2.py
        input: wrong
        expected-output: 'Enter a command: '
        comparison-method: exact
        timeout: 1
    - name: task2-2
      id: task2-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task2-2
        setup-command: ''
        command: python3 Task2.py
        input: sys.in
        expected-output: команда принята
        comparison-method: contains
        timeout: 1
    - name: task2-3
      id: task2-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task2-3
        setup-command: ''
        command: python3 Task2.py
        input: sys.in_random
        expected-output: команда принята
        comparison-method: contains
        timeout: 1
    - name: task2-4
      id: task2-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task2-4
        setup-command: ''
        command: python3 Task2.py
        input: random_sys.in
        expected-output: 'Enter a command: '
        comparison-method: exact
        timeout: 1
    - name: task4-4
      id: task4-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task4-4
        setup-command: ''
        command: python3 Task4.py 3 3 /
        input: ''
        expected-output: '1.0'
        comparison-method: exact
        timeout: 1
    - name: task4-2
      id: task4-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task4-2
        setup-command: ''
        command: python3 Task4.py 2 3 -
        input: ''
        expected-output: "-1"
        comparison-method: exact
        timeout: 1
    - name: task5-1
      id: task5-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task5-1
        setup-command: ''
        command: python3 Task5.py
        input: "one\ntwo\nthree\n "
        expected-output: |-
          3
          3
          5
        comparison-method: exact
        timeout: 1
    - name: task4-1
      id: task4-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task4-1
        setup-command: ''
        command: python3 Task4.py 2 3 +
        input: ''
        expected-output: '5'
        comparison-method: exact
        timeout: 1
    - name: task4-3
      id: task4-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task4-3
        setup-command: ''
        command: python3 Task3.py 2 3 *
        input: ''
        expected-output: '6'
        comparison-method: exact
        timeout: 1
    - name: task3
      id: task3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: task3
        setup-command: touch a.txt
        command: python3 Task3.py test123 a.txt | echo "$(<a.txt )"
        input: ''
        expected-output: test123
        comparison-method: contains
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TASK1-1_RESULTS: "${{steps.task1-1.outputs.result}}"
        TASK1-2_RESULTS: "${{steps.task1-2.outputs.result}}"
        TASK1-3_RESULTS: "${{steps.task1-3.outputs.result}}"
        TASK1-4_RESULTS: "${{steps.task1-4.outputs.result}}"
        TASK2-1_RESULTS: "${{steps.task2-1.outputs.result}}"
        TASK2-2_RESULTS: "${{steps.task2-2.outputs.result}}"
        TASK2-3_RESULTS: "${{steps.task2-3.outputs.result}}"
        TASK2-4_RESULTS: "${{steps.task2-4.outputs.result}}"
        TASK4-4_RESULTS: "${{steps.task4-4.outputs.result}}"
        TASK4-2_RESULTS: "${{steps.task4-2.outputs.result}}"
        TASK5-1_RESULTS: "${{steps.task5-1.outputs.result}}"
        TASK4-1_RESULTS: "${{steps.task4-1.outputs.result}}"
        TASK4-3_RESULTS: "${{steps.task4-3.outputs.result}}"
        TASK3_RESULTS: "${{steps.task3.outputs.result}}"
      with:
        runners: task1-1,task1-2,task1-3,task1-4,task2-1,task2-2,task2-3,task2-4,task4-4,task4-2,task5-1,task4-1,task4-3,task3
